query repoPullRequests($organization: String!, $repository: String!, $endCursor: String) {
  organization(login: $organization) {
    repository(name: $repository) {
      pullRequests(first: 100, after: $endCursor) {
        nodes {
          author {
            login
          }
          createdAt
          title
          body
          repository {
            name
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}
