query userPullRequests($login: String!, $endCursor: String) {
  user(login: $login) {
    pullRequests(first: 100, after: $endCursor) {
      nodes {
        author {
          login
        }
        createdAt
        title
        body
        repository {
          name
          owner {
            login
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
